import { execFileSync } from 'node:child_process';
import { existsSync, lstatSync, readFileSync, readdirSync, readlinkSync } from 'node:fs';
import { basename, dirname, isAbsolute, join, resolve } from 'node:path';
import { parse, stringify } from 'yaml';
import { EvaluationService } from '../evaluation/service.js';
import type { ImprovementProposal } from '../../domain/v4/contracts.js';
import { DomainError } from '../../domain/policy.js';
import type { CandidateAuthorization, CandidateDecision, CandidateManifest, CandidateMode, CandidateRequest, CandidateSnapshot, CandidateStatus, ChangePlan, CleanupReceipt, CodeReviewReport, EnvironmentManifest, ImpactReport, RegressionComparison, ScopeReport, WorkspaceLease } from '../../domain/v5/contracts.js';
import { hash, stableJson } from '../../infrastructure/hashing.js';
import { atomicWrite } from '../../infrastructure/v2/atomic.js';
import { assertIdentifier, ensurePrivateDirectory, within } from '../../infrastructure/v2/paths.js';
import { defaultStateRoot } from '../../infrastructure/run-store.js';
import { coreRoot } from '../../infrastructure/validation.js';
import { validateV5 } from '../../infrastructure/v5/validation.js';

const now = (): string => new Date().toISOString();
const opaqueId = (prefix: string, value: unknown): string => `${prefix}_${hash(stableJson(value)).slice('sha256:'.length, 'sha256:'.length + 32)}`;
const withoutHash = <T extends Record<string, unknown>>(value: T, field: string): T => ({ ...value, [field]: null }) as T;
const hashed = <T extends Record<string, unknown>>(value: T, field: string): T => ({ ...value, [field]: hash(stableJson(withoutHash(value, field))) }) as T;

class CandidateFiles {
  readonly root: string;
  constructor(stateRoot: string | undefined, readonly profileId: string) {
    assertIdentifier(profileId, 'profile_id');
    const base = resolve(stateRoot ?? defaultStateRoot());
    if (within(resolve(coreRoot), base)) throw new DomainError('STATE_IN_REPOSITORY', 'Estado v0.5 deve ficar fora do repositório.');
    this.root = join(base, 'profiles', profileId, 'candidates');
    ensurePrivateDirectory(this.root);
  }
  dir(candidateId: string): string { assertIdentifier(candidateId, 'candidate_id'); return join(this.root, candidateId); }
  ensure(candidateId: string): string { const path = this.dir(candidateId); ensurePrivateDirectory(path); return path; }
  write(candidateId: string, name: string, value: unknown): void { this.validate(name, value); const path = join(this.ensure(candidateId), name); ensurePrivateDirectory(dirname(path)); atomicWrite(path, stringify(value)); }
  writeText(candidateId: string, name: string, value: string): void { const path = join(this.ensure(candidateId), name); ensurePrivateDirectory(dirname(path)); atomicWrite(path, value); }
  read<T>(candidateId: string, name: string): T { try { const value = parse(readFileSync(join(this.dir(candidateId), name), 'utf8')); this.validate(name, value); return value as T; } catch (error) { if (error instanceof DomainError) throw error; throw new DomainError('CANDIDATE_NOT_FOUND', 'Artefato de candidate não encontrado.'); } }
  has(candidateId: string): boolean { return existsSync(join(this.dir(candidateId), 'manifest.yaml')); }
  private validate(name: string, value: unknown): void {
    const schema = name === 'manifest.yaml' ? 'candidate-manifest'
      : name === 'request.yaml' ? 'candidate-request'
      : name === 'authorization.yaml' || name === 'freeze-authorization.yaml' || /\/authorization\.yaml$/.test(name) ? 'candidate-authorization'
      : name === 'lease.yaml' ? 'workspace-lease'
      : name === 'environment.yaml' ? 'environment-manifest'
      : name === 'plan.yaml' ? 'change-plan'
      : name.endsWith('/scope.yaml') || name.endsWith('/change-set.yaml') ? 'change-set'
      : name.endsWith('/snapshot.yaml') ? 'candidate-snapshot'
      : name.endsWith('/comparison.yaml') ? 'regression-comparison'
      : name.endsWith('/review.yaml') ? 'code-review-report'
      : name.endsWith('/impact-report.yaml') ? 'impact-report'
      : name.startsWith('decisions/') && name.endsWith('.yaml') ? 'candidate-decision'
      : name.startsWith('cleanup/') && name.endsWith('.yaml') ? 'cleanup-receipt'
      : null;
    if (schema) validateV5(schema, value);
  }
}

export class CandidateService {
  private readonly files: CandidateFiles;
  private readonly proposals: EvaluationService;
  constructor(readonly stateRoot: string | undefined, readonly profileId: string) {
    this.files = new CandidateFiles(stateRoot, profileId);
    this.proposals = new EvaluationService(stateRoot, profileId);
  }

  request(proposalId: string, repositoryPath: string, allowedPaths: string[], mode: CandidateMode = 'dry-run', requestedBase?: string): CandidateManifest {
    if (mode === 'disabled') throw new DomainError('CANDIDATE_DISABLED', 'Pipeline v0.5 está disabled; nenhuma candidate pode ser criada.');
    const proposal = this.proposals.showProposal(proposalId);
    this.assertProposal(proposal);
    const repo = this.repository(repositoryPath);
    const paths = this.normalizeAllowedPaths(allowedPaths);
    if (paths.length === 0) throw new DomainError('SCOPE_REQUIRED', 'Candidate exige uma allowlist de paths explícita.');
    const requestedRef = requestedBase ?? this.tryGit(repo, ['symbolic-ref', '--short', '-q', 'HEAD']) ?? 'HEAD';
    const baseSha = this.git(repo, ['rev-parse', '--verify', `${requestedRef}^{commit}`]);
    const mainFingerprint = this.mainFingerprint(repo);
    const repositoryIdentity = this.repositoryIdentity(repo);
    const candidateId = opaqueId('cand', { proposal: proposal.proposal_id, version: 1, profile: this.profileId, repositoryIdentity, baseSha, revision: 1 });
    if (this.files.has(candidateId)) { const existing = this.show(candidateId); if (existing.mode !== mode || stableJson(existing.allowed_paths) !== stableJson(paths)) throw new DomainError('SCOPE_REAPPROVAL_REQUIRED', 'Candidate existente possui mode ou scope diferente; nova autorização é necessária.'); return existing; }
    const budget = { files: 20, added_lines: 500, deleted_lines: 300 };
    const manifest: CandidateManifest = { schema_version: 5, candidate_id: candidateId, proposal: { id: proposal.proposal_id, version: 1, status: proposal.status, target_component: proposal.target.component_id }, profile_id: this.profileId, mode, status: 'REQUESTED', revision: 1,
      repository: { path: repo, identity: repositoryIdentity, base_ref: requestedRef, base_sha: baseSha, main_dirty: this.status(repo).length > 0, dirty_paths_count: this.status(repo).split('\n').filter(Boolean).length }, allowed_paths: paths, diff_budget: budget, branch: null, baseline_path: null, candidate_path: null, authorization_hash: null, environment_hash: null, snapshot: null, comparison_hash: null, review_hash: null, report_hash: null, main_fingerprint_before: mainFingerprint, main_fingerprint_after: null, created_at: now() };
    const request: CandidateRequest = hashed({ schema_version: 1 as const, candidate_id: candidateId, proposal: { id: proposal.proposal_id, version: 1, decision: 'ApprovedForCandidate' as const }, profile_id: this.profileId, repository: { path: repo, identity: repositoryIdentity, requested_base: requestedRef, resolved_base_sha: baseSha }, requested_target: { component: proposal.target.component_id, paths }, mode, requested_by: 'user', created_at: manifest.created_at, idempotency_key: `${proposal.proposal_id}:1:${baseSha}:1`, payload_hash: '' }, 'payload_hash');
    const plan: ChangePlan = hashed({ schema_version: 1 as const, candidate_id: candidateId, revision: 1, hypothesis: proposal.change.intended_behavior, target_component: proposal.target.component_id, base_sha: baseSha, allowed_paths: paths, steps: ['add_failing_regression', 'apply_minimal_change', 'run_targeted_checks', 'run_full_candidate_suite'], non_goals: proposal.change.non_goals, diff_budget: budget, verification_commands: ['npm run check'], frozen_at: null, plan_hash: '' }, 'plan_hash');
    manifest.status = 'PLANNED';
    this.files.write(candidateId, 'request.yaml', request); this.files.write(candidateId, 'manifest.yaml', manifest); this.files.write(candidateId, 'plan.yaml', plan);
    return manifest;
  }

  show(candidateId: string): CandidateManifest { return this.files.read<CandidateManifest>(candidateId, 'manifest.yaml'); }
  plan(candidateId: string): ChangePlan { return this.files.read<ChangePlan>(candidateId, 'plan.yaml'); }
  authorization(candidateId: string): CandidateAuthorization { return this.files.read<CandidateAuthorization>(candidateId, 'authorization.yaml'); }
  freezeAuthorization(candidateId: string): CandidateAuthorization { return this.files.read<CandidateAuthorization>(candidateId, 'freeze-authorization.yaml'); }

  authorize(candidateId: string, expiresInSeconds: number): CandidateAuthorization {
    const manifest = this.show(candidateId); if (manifest.status !== 'PLANNED' && manifest.status !== 'CHANGES_REQUESTED') throw new DomainError('INVALID_CANDIDATE_STATE', 'Candidate não está aguardando autorização.');
    if (!Number.isInteger(expiresInSeconds) || expiresInSeconds <= 0 || expiresInSeconds > 24 * 60 * 60) throw new DomainError('INVALID_EXPIRY', 'Expiração deve estar entre 1 segundo e 24 horas.');
    const currentSha = this.git(manifest.repository.path, ['rev-parse', '--verify', 'HEAD']); if (currentSha !== manifest.repository.base_sha) throw new DomainError('BASE_DRIFT', 'HEAD mudou desde o intake; nova candidate é necessária.');
    const authorizedAt = new Date(); const auth: CandidateAuthorization = hashed({ schema_version: 1 as const, authorization_id: opaqueId('auth', { candidate: candidateId, revision: manifest.revision, base: manifest.repository.base_sha }), candidate_id: candidateId, proposal_ref: { id: manifest.proposal.id, version: manifest.proposal.version }, profile_id: this.profileId, repository_identity: manifest.repository.identity, base_sha: manifest.repository.base_sha, revision: manifest.revision, allowed_paths: manifest.allowed_paths, allowed_operations: ['candidate_write', 'regression_fixture'], forbidden_operations: ['network', 'git_remote', 'main_checkout_write', 'baseline_write', 'merge', 'rebase', 'cherry-pick', 'push', 'fetch', 'pull', 'tag', 'external_write'], diff_budget: manifest.diff_budget, authorized_by: 'user' as const, authorized_at: authorizedAt.toISOString(), expires_at: new Date(authorizedAt.getTime() + expiresInSeconds * 1000).toISOString(), scope_hash: null, payload_hash: '' }, 'payload_hash');
    this.files.write(candidateId, 'authorization.yaml', auth); this.update(candidateId, { status: 'AUTHORIZED', authorization_hash: auth.payload_hash }); return auth;
  }

  authorizeFreeze(candidateId: string, expiresInSeconds: number): CandidateAuthorization {
    const manifest = this.show(candidateId);
    if (manifest.status !== 'BUILDING') throw new DomainError('INVALID_CANDIDATE_STATE', 'Freeze exige candidate editável com Scope Guard aprovado.');
    this.assertAuthorization(manifest);
    if (!Number.isInteger(expiresInSeconds) || expiresInSeconds <= 0 || expiresInSeconds > 24 * 60 * 60) throw new DomainError('INVALID_EXPIRY', 'Expiração deve estar entre 1 segundo e 24 horas.');
    const scope = this.scope(candidateId);
    if (!scope.passed) throw new DomainError('SCOPE_VIOLATION', scope.reason ?? 'Candidate fora do escopo.');
    const authorizedAt = new Date();
    const auth: CandidateAuthorization = hashed({ schema_version: 1 as const, authorization_id: opaqueId('freeze_auth', { candidate: candidateId, revision: manifest.revision, scope: scope.diff_hash }), candidate_id: candidateId, proposal_ref: { id: manifest.proposal.id, version: manifest.proposal.version }, profile_id: this.profileId, repository_identity: manifest.repository.identity, base_sha: manifest.repository.base_sha, revision: manifest.revision, allowed_paths: manifest.allowed_paths, allowed_operations: ['local_snapshot'], forbidden_operations: ['network', 'git_remote', 'main_checkout_write', 'baseline_write', 'merge', 'rebase', 'cherry-pick', 'push', 'fetch', 'pull', 'tag', 'external_write'], diff_budget: manifest.diff_budget, authorized_by: 'user' as const, authorized_at: authorizedAt.toISOString(), expires_at: new Date(authorizedAt.getTime() + expiresInSeconds * 1000).toISOString(), scope_hash: scope.diff_hash, payload_hash: '' }, 'payload_hash');
    this.files.write(candidateId, 'freeze-authorization.yaml', auth);
    return auth;
  }

  create(candidateId: string): CandidateManifest {
    let manifest = this.show(candidateId); if (manifest.status !== 'AUTHORIZED') { if (manifest.status === 'WORKSPACE_READY' || manifest.status === 'BUILDING' || manifest.status === 'FROZEN') return manifest; throw new DomainError('AUTHORIZATION_REQUIRED', 'Crie a workspace somente depois da autorização humana.'); }
    this.assertAuthorization(manifest);
    if (manifest.mode === 'dry-run') return manifest;
    this.assertNetworkSandbox(); this.assertNoActiveHooks(manifest.repository.path);
    if (manifest.baseline_path && manifest.candidate_path && existsSync(manifest.baseline_path) && existsSync(manifest.candidate_path) && manifest.branch) { const environment = this.files.read<EnvironmentManifest>(candidateId, 'environment.yaml'); const lease: WorkspaceLease = { schema_version: 1, lease_id: opaqueId('lease', { candidateId, revision: manifest.revision }), candidate_id: candidateId, owner_run_id: candidateId, repository_identity: manifest.repository.identity, base_sha: manifest.repository.base_sha, baseline_path: manifest.baseline_path, candidate_path: manifest.candidate_path, locked: true, issued_at: now(), heartbeat_at: now(), expires_at: this.authorization(candidateId).expires_at }; this.files.write(candidateId, 'lease.yaml', lease); return this.update(candidateId, { status: 'WORKSPACE_READY', environment_hash: environment.payload_hash }); }
    const repo = manifest.repository.path; const candidateRoot = this.files.ensure(candidateId); const worktrees = join(candidateRoot, 'worktrees'); ensurePrivateDirectory(worktrees);
    const baseline = join(worktrees, 'baseline'); const candidate = join(worktrees, 'candidate'); if (existsSync(baseline) || existsSync(candidate)) throw new DomainError('WORKTREE_COLLISION', 'Worktree registrada já existe; não será sobrescrita.');
    const short = candidateId.slice(-12); const branch = `megabrain/candidate/${short}-r${manifest.revision}-${this.slug(manifest.proposal.target_component)}`;
    try {
      this.git(repo, ['worktree', 'add', '--detach', baseline, manifest.repository.base_sha]);
      this.git(repo, ['worktree', 'add', '--no-track', '-b', branch, candidate, manifest.repository.base_sha]);
      this.git(repo, ['worktree', 'lock', baseline, '--reason', `megabrain candidate ${candidateId} baseline`]);
      this.git(repo, ['worktree', 'lock', candidate, '--reason', `megabrain candidate ${candidateId} active`]);
    } catch (error) {
      if (existsSync(baseline)) this.tryGit(repo, ['worktree', 'remove', baseline]);
      throw error;
    }
    if (this.tryGit(repo, ['config', '--get', `branch.${branch}.remote`])) throw new DomainError('GIT_OPERATION_BLOCKED', 'Candidate branch não pode possuir upstream.');
    const environment = this.environment(manifest, baseline); this.files.write(candidateId, 'environment.yaml', environment);
    const lease: WorkspaceLease = { schema_version: 1, lease_id: opaqueId('lease', { candidateId, revision: manifest.revision }), candidate_id: candidateId, owner_run_id: candidateId, repository_identity: manifest.repository.identity, base_sha: manifest.repository.base_sha, baseline_path: baseline, candidate_path: candidate, locked: true, issued_at: now(), heartbeat_at: now(), expires_at: this.authorization(candidateId).expires_at };
    this.files.write(candidateId, 'lease.yaml', lease);
    manifest = this.update(candidateId, { status: 'WORKSPACE_READY', branch, baseline_path: baseline, candidate_path: candidate, environment_hash: environment.payload_hash });
    this.assertMainUnchanged(manifest); return manifest;
  }

  build(candidateId: string, podeFazer: boolean, patchFile: string): ScopeReport {
    const manifest = this.show(candidateId); if (!podeFazer) throw new DomainError('AUTHORIZATION_REQUIRED', 'Edição exige --pode-fazer nesta ação.'); if (manifest.mode !== 'supervised') throw new DomainError('CANDIDATE_MODE_BLOCKED', 'Edição só é permitida no modo supervised.');
    if (manifest.status !== 'WORKSPACE_READY' && manifest.status !== 'BUILDING') throw new DomainError('INVALID_CANDIDATE_STATE', 'Candidate não está em fase editável.'); this.assertAuthorization(manifest); if (!manifest.candidate_path) throw new DomainError('WORKSPACE_MISSING', 'Worktree candidate não existe.');
    const patch = resolve(patchFile); if (!existsSync(patch) || lstatSync(patch).isSymbolicLink()) throw new DomainError('PATCH_BLOCKED', 'Patch ausente ou inseguro.'); if (readFileSync(patch).byteLength > 2_000_000) throw new DomainError('INPUT_TOO_LARGE', 'Patch maior que 2 MB.');
    this.git(manifest.candidate_path, ['apply', '--whitespace=error', '--recount', patch]); this.assertMainUnchanged(manifest); const scope = this.scope(candidateId); this.update(candidateId, { status: scope.passed ? 'BUILDING' : 'BLOCKED' }); if (!scope.passed) throw new DomainError('SCOPE_VIOLATION', scope.reason ?? 'Candidate fora do escopo.'); return scope;
  }

  scope(candidateId: string): ScopeReport {
    const manifest = this.show(candidateId); if (!manifest.candidate_path) throw new DomainError('WORKSPACE_MISSING', 'Worktree candidate não existe.');
    const candidate = manifest.candidate_path; const names = new Set<string>(); const diff = this.tryGit(candidate, ['diff', '--name-status', '--find-renames', manifest.repository.base_sha]) ?? '';
    for (const line of diff.split('\n').filter(Boolean)) { const fields = line.split('\t'); if (fields.length > 1) { names.add(fields[fields.length - 1]!); if ((fields[0] ?? '').startsWith('R') && fields.length > 2) names.add(fields[1]!); } }
    for (const path of (this.tryGit(candidate, ['ls-files', '--others', '--exclude-standard']) ?? '').split('\n').filter(Boolean)) names.add(path);
    const files = [...names].sort(); let added = 0; let deleted = 0; const numstat = this.tryGit(candidate, ['diff', '--numstat', manifest.repository.base_sha]) ?? '';
    for (const line of numstat.split('\n').filter(Boolean)) { const [a, d] = line.split('\t'); if (a === '-') continue; added += Number(a) || 0; deleted += Number(d) || 0; }
    for (const file of files) if (!(numstat.split('\n').some(line => line.endsWith(`\t${file}`)))) { const path = join(candidate, file); const stat = this.tryLstat(path); if (stat && !stat.isSymbolicLink() && stat.isFile()) { const data = readFileSync(path); if (!data.includes(0)) added += data.length === 0 ? 0 : data.toString('utf8').split('\n').length; } }
    const outOfScope = files.filter(file => !manifest.allowed_paths.some(pattern => this.matches(pattern, file))); const symlinks = files.filter(file => this.tryLstat(join(candidate, file))?.isSymbolicLink() === true); const binaries = files.filter(file => { const path = join(candidate, file); const stat = this.tryLstat(path); return Boolean(stat && !stat.isSymbolicLink() && stat.isFile() && readFileSync(path).includes(0)); });
    const sensitivePaths = files.filter(file => /(^|\/)(\.env(?:\.|$)|.*secret.*|.*credential.*|id_rsa|.*\.pem$)/i.test(file)); const lockfiles = files.filter(file => /(^|\/)(package-lock\.json|npm-shrinkwrap\.json|yarn\.lock|pnpm-lock\.yaml)$/.test(file));
    const lockfileUnplanned = lockfiles.filter(file => !manifest.allowed_paths.some(pattern => this.matches(pattern, file))); const reason = outOfScope.length ? 'path fora da allowlist' : symlinks.length ? 'symlink novo ou alterado' : binaries.length ? 'binário fora do piloto' : sensitivePaths.length ? 'path sensível exige revisão adicional' : lockfileUnplanned.length ? 'lockfile sem intenção explícita' : files.length > manifest.diff_budget.files ? 'diff budget de arquivos excedido' : added > manifest.diff_budget.added_lines ? 'diff budget de linhas adicionadas excedido' : deleted > manifest.diff_budget.deleted_lines ? 'diff budget de linhas removidas excedido' : null;
    const report: ScopeReport = hashed({ schema_version: 1 as const, candidate_id: candidateId, revision: manifest.revision, files, out_of_scope: [...new Set([...outOfScope, ...lockfileUnplanned])].sort(), added_lines: added, deleted_lines: deleted, symlinks, binaries, sensitive_paths: sensitivePaths, passed: reason === null, reason, diff_hash: hash(stableJson({ base: manifest.repository.base_sha, files, added, deleted })) }, 'diff_hash');
    this.files.write(candidateId, `revisions/${String(manifest.revision).padStart(3, '0')}/scope.yaml`, report); return report;
  }

  freeze(candidateId: string, podeFazer: boolean): CandidateSnapshot {
    if (!podeFazer) throw new DomainError('AUTHORIZATION_REQUIRED', 'Freeze exige --pode-fazer nesta ação.');
    const manifest = this.show(candidateId); if (manifest.status !== 'BUILDING') throw new DomainError('INVALID_CANDIDATE_STATE', 'Freeze exige candidate editável e scope check aprovado.'); if (!manifest.candidate_path || !manifest.branch || !manifest.environment_hash) throw new DomainError('WORKSPACE_MISSING', 'Workspace ou ambiente ausente.'); this.assertAuthorization(manifest); this.assertMainUnchanged(manifest);
    const scope = this.scope(candidateId); if (!scope.passed) throw new DomainError('SCOPE_VIOLATION', 'Scope Guard não passou.'); this.assertFreezeAuthorization(manifest, scope);
    this.git(manifest.candidate_path, ['add', '--', ...scope.files]);
    const afterStage = this.scope(candidateId); if (!afterStage.passed || afterStage.diff_hash !== scope.diff_hash) throw new DomainError('SCOPE_STALE', 'O change set mudou durante o freeze; revise e autorize novamente.');
    const parent = this.git(manifest.candidate_path, ['rev-parse', 'HEAD']); const staged = this.git(manifest.candidate_path, ['diff', '--cached', '--name-status']); if (!staged) throw new DomainError('EMPTY_CHANGE_SET', 'Nenhuma mudança explícita para congelar.');
    this.git(manifest.candidate_path, ['commit', '-m', `MegaBrain candidate ${candidateId} revision ${manifest.revision}`], { GIT_AUTHOR_NAME: 'MegaBrain Candidate', GIT_AUTHOR_EMAIL: 'megabrain@invalid', GIT_COMMITTER_NAME: 'MegaBrain Candidate', GIT_COMMITTER_EMAIL: 'megabrain@invalid' }); const commit = this.git(manifest.candidate_path, ['rev-parse', 'HEAD']); const tree = this.git(manifest.candidate_path, ['rev-parse', `${commit}^{tree}`]); const snapshot: CandidateSnapshot = { schema_version: 1, candidate_id: candidateId, revision: manifest.revision, branch: manifest.branch, base_sha: manifest.repository.base_sha, commit_sha: commit, tree_sha: tree, parent_sha: parent, change_set_hash: scope.diff_hash, environment_hash: manifest.environment_hash, frozen_at: now() };
    if (this.status(manifest.candidate_path).length) { this.update(candidateId, { status: 'BLOCKED' }); throw new DomainError('CANDIDATE_DIRTY', 'Worktree mudou durante o commit; snapshot não será avaliado.'); }
    this.files.write(candidateId, `revisions/${String(manifest.revision).padStart(3, '0')}/change-set.yaml`, scope); this.files.write(candidateId, `revisions/${String(manifest.revision).padStart(3, '0')}/snapshot.yaml`, snapshot); this.update(candidateId, { status: 'FROZEN', snapshot: { commit_sha: commit, tree_sha: tree, change_set_hash: scope.diff_hash } }); this.assertMainUnchanged(manifest); return snapshot;
  }

  evaluate(candidateId: string): RegressionComparison {
    let manifest = this.show(candidateId); if (manifest.status !== 'FROZEN' && manifest.status !== 'EVALUATING') throw new DomainError('INVALID_CANDIDATE_STATE', 'Avaliação exige snapshot congelado.'); if (!manifest.snapshot || !manifest.baseline_path || !manifest.candidate_path || !manifest.environment_hash) throw new DomainError('WORKSPACE_MISSING', 'Snapshot, worktrees ou ambiente ausente.'); this.assertFrozenCandidate(manifest); this.assertMainUnchanged(manifest);
    this.update(candidateId, { status: 'EVALUATING' }); let baselinePath: string | null = null; let candidatePath: string | null = null; let baseline: ReturnType<CandidateService['runCheck']>; let candidate: ReturnType<CandidateService['runCheck']>; try { baselinePath = this.evaluationWorktree(manifest, 'baseline', manifest.repository.base_sha); candidatePath = this.evaluationWorktree(manifest, 'candidate', manifest.snapshot.commit_sha); baseline = this.runCheck(baselinePath); candidate = this.runCheck(candidatePath); } finally { if (baselinePath) this.removeEvaluationWorktree(manifest.repository.path, baselinePath); if (candidatePath) this.removeEvaluationWorktree(manifest.repository.path, candidatePath); }
    const classification: RegressionComparison['causal_case']['classification'] = baseline!.status === 'failed' && candidate!.status === 'passed' ? 'Improved' : baseline!.status === 'passed' && candidate!.status === 'passed' ? 'Equivalent' : baseline!.status === 'passed' && candidate!.status === 'failed' ? 'Regressed' : 'Inconclusive';
    const overall: RegressionComparison['overall'] = !baseline!.available || !candidate!.available ? 'BlockedByEnvironment' : classification === 'Improved' || classification === 'Equivalent' ? 'EligibleForReview' : classification === 'Regressed' ? 'BlockedByHardRegression' : 'NeedsMoreEvidence'; const comparison: RegressionComparison = hashed({ schema_version: 1 as const, candidate_id: candidateId, revision: manifest.revision, snapshot_commit: manifest.snapshot.commit_sha, baseline_sha: manifest.repository.base_sha, environment_hash: manifest.environment_hash, causal_case: { baseline: baseline!.status, candidate: candidate!.status, classification }, hard_gates: { main_unchanged: true, scope_passed: true, policy_violations: 0, profile_leaks: 0, false_successes: 0 }, metrics: { baseline_exit: baseline!.exit, candidate_exit: candidate!.exit, baseline_duration_ms: baseline!.duration, candidate_duration_ms: candidate!.duration }, overall, comparison_hash: '' }, 'comparison_hash');
    this.files.write(candidateId, `revisions/${String(manifest.revision).padStart(3, '0')}/comparison.yaml`, comparison); manifest = this.update(candidateId, { status: overall === 'EligibleForReview' ? 'PASSED' : overall === 'BlockedByHardRegression' ? 'FAILED' : overall === 'BlockedByEnvironment' ? 'BLOCKED' : 'INCONCLUSIVE', comparison_hash: comparison.comparison_hash }); this.assertMainUnchanged(manifest); return comparison;
  }

  review(candidateId: string): CodeReviewReport {
    const manifest = this.show(candidateId); if (!manifest.snapshot || !manifest.candidate_path) throw new DomainError('SNAPSHOT_REQUIRED', 'Review exige snapshot.'); const names = (this.tryGit(manifest.candidate_path, ['diff', '--name-only', `${manifest.repository.base_sha}..${manifest.snapshot.commit_sha}`]) ?? '').split('\n').filter(Boolean).sort(); const risky = names.filter(path => /(^|\/)(policies?|auth|redact|hooks?|\.github\/workflows|package-lock\.json)/i.test(path)); const findings = risky.map((path, index) => ({ id: opaqueId('review', { candidateId, path, index }), severity: 'P1' as const, path, summary: 'Path de alto risco exige revisão humana específica antes de aceitar.' })); const report: CodeReviewReport = hashed({ schema_version: 1 as const, candidate_id: candidateId, revision: manifest.revision, snapshot_commit: manifest.snapshot.commit_sha, mode: 'read_only' as const, changed_paths: names, findings, recommendation: findings.length ? 'blocked' as const : 'human_decision_required' as const, review_hash: '' }, 'review_hash'); this.files.write(candidateId, `revisions/${String(manifest.revision).padStart(3, '0')}/review.yaml`, report); this.update(candidateId, { status: 'REVIEWED', review_hash: report.review_hash }); return report;
  }

  report(candidateId: string): ImpactReport {
    const manifest = this.show(candidateId); if (!manifest.snapshot || !manifest.comparison_hash || !manifest.review_hash) throw new DomainError('REPORT_PREREQUISITES_MISSING', 'Report exige snapshot, comparação e review.'); const comparison = this.files.read<RegressionComparison>(candidateId, `revisions/${String(manifest.revision).padStart(3, '0')}/comparison.yaml`); const review = this.files.read<CodeReviewReport>(candidateId, `revisions/${String(manifest.revision).padStart(3, '0')}/review.yaml`); const hard = comparison.overall === 'EligibleForReview' && comparison.hard_gates.main_unchanged && comparison.hard_gates.scope_passed && !review.findings.some(item => item.severity === 'P0' || item.severity === 'P1'); const recommendation: ImpactReport['recommendation'] = hard ? 'RecommendAcceptForManualIntegration' : comparison.overall === 'BlockedByHardRegression' || review.findings.some(item => item.severity === 'P0' || item.severity === 'P1') ? 'RecommendReject' : comparison.overall === 'NeedsMoreEvidence' || comparison.overall === 'BlockedByEnvironment' ? 'InsufficientEvidence' : 'RecommendRequestChanges'; const value: ImpactReport = hashed({ schema_version: 1 as const, candidate_id: candidateId, revision: manifest.revision, proposal_ref: `${manifest.proposal.id}@${manifest.proposal.version}`, base_sha: manifest.repository.base_sha, snapshot_commit: manifest.snapshot.commit_sha, change_set_hash: manifest.snapshot.change_set_hash, comparison_hash: comparison.comparison_hash, review_hash: review.review_hash, hard_gates_passed: hard, recommendation, changed_paths: review.changed_paths, limitations: ['Aceitação não executa merge, push, PR ou alteração no checkout principal.'], report_hash: '' }, 'report_hash'); this.files.write(candidateId, `revisions/${String(manifest.revision).padStart(3, '0')}/impact-report.yaml`, value); this.files.writeText(candidateId, `revisions/${String(manifest.revision).padStart(3, '0')}/impact-report.md`, this.markdown(value, comparison, review)); this.update(candidateId, { status: 'AWAITING_DECISION', report_hash: value.report_hash }); return value;
  }

  decide(candidateId: string, decision: CandidateDecision['decision'], reportHash: string, reason: string): CandidateDecision {
    const manifest = this.show(candidateId); const report = this.files.read<ImpactReport>(candidateId, `revisions/${String(manifest.revision).padStart(3, '0')}/impact-report.yaml`); if (!manifest.snapshot || manifest.report_hash !== reportHash || report.report_hash !== reportHash || report.report_hash !== hash(stableJson(withoutHash(report as unknown as Record<string, unknown>, 'report_hash')))) throw new DomainError('STALE_REPORT', 'Decisão deve referenciar o Impact Report exato da revisão.'); if (decision === 'AcceptedForManualIntegration' && report.recommendation !== 'RecommendAcceptForManualIntegration') throw new DomainError('ACCEPTANCE_BLOCKED', 'Aceitação manual exige recomendação técnica de aceite e hard gates aprovados.'); if (!['AcceptedForManualIntegration', 'ChangesRequested', 'Rejected', 'Deferred', 'NeedsEvidence'].includes(decision)) throw new DomainError('INVALID_DECISION', 'Decisão humana inválida.'); const value: CandidateDecision = hashed({ schema_version: 1 as const, decision_id: opaqueId('decision', { candidateId, revision: manifest.revision, decision, reportHash }), candidate_id: candidateId, revision: manifest.revision, snapshot_commit: manifest.snapshot.commit_sha, report_hash: reportHash, decision, decided_by: 'user' as const, reason, conditions: [], decided_at: now(), payload_hash: '' }, 'payload_hash'); this.files.write(candidateId, `decisions/${value.decision_id}.yaml`, value);
    if (decision === 'ChangesRequested') { this.requestChanges(candidateId, reason); return value; }
    const next: CandidateStatus = decision === 'AcceptedForManualIntegration' ? 'ACCEPTED_FOR_MANUAL_INTEGRATION' : decision === 'Rejected' ? 'REJECTED' : decision === 'Deferred' ? 'DEFERRED' : 'INCONCLUSIVE'; this.update(candidateId, { status: next }); return value;
  }

  requestChanges(candidateId: string, feedback: string): CandidateManifest {
    const manifest = this.show(candidateId); if (manifest.status !== 'AWAITING_DECISION' && manifest.status !== 'REVIEWED' && manifest.status !== 'PASSED') throw new DomainError('INVALID_CANDIDATE_STATE', 'Request Changes exige report disponível.'); this.files.writeText(candidateId, `decisions/feedback-r${manifest.revision}.txt`, feedback.slice(0, 20_000)); if (manifest.authorization_hash) { try { this.files.write(candidateId, `revisions/${String(manifest.revision).padStart(3, '0')}/authorization.yaml`, this.authorization(candidateId)); } catch { /* a revision without authorization remains auditable by its plan */ } } const revision = manifest.revision + 1; const currentPlan = this.plan(candidateId); const nextPlan: ChangePlan = hashed({ schema_version: 1 as const, candidate_id: candidateId, revision, hypothesis: currentPlan.hypothesis, target_component: manifest.proposal.target_component, base_sha: manifest.repository.base_sha, allowed_paths: manifest.allowed_paths, steps: currentPlan.steps, non_goals: currentPlan.non_goals, diff_budget: manifest.diff_budget, verification_commands: ['npm run check'], frozen_at: null, plan_hash: '' }, 'plan_hash'); this.files.write(candidateId, 'plan.yaml', nextPlan); return this.update(candidateId, { status: 'CHANGES_REQUESTED', revision, authorization_hash: null, snapshot: null, comparison_hash: null, review_hash: null, report_hash: null });
  }

  cleanup(candidateId: string, confirm: boolean): CleanupReceipt {
    if (!confirm) throw new DomainError('CONFIRMATION_REQUIRED', 'Cleanup exige confirmação humana explícita.'); const manifest = this.show(candidateId); const removed: string[] = []; for (const path of [manifest.baseline_path, manifest.candidate_path]) if (path) { if (!within(join(this.files.dir(candidateId), 'worktrees'), path)) throw new DomainError('PATH_BLOCKED', 'Registry aponta para worktree fora do candidate.'); if (existsSync(path)) { if (this.status(path).length) throw new DomainError('DIRTY_WORKTREE', 'Worktree suja não é removida automaticamente.'); this.tryGit(manifest.repository.path, ['worktree', 'unlock', path]); this.git(manifest.repository.path, ['worktree', 'remove', path]); removed.push(path); } }
    const receipt: CleanupReceipt = hashed({ schema_version: 1 as const, cleanup_id: opaqueId('cleanup', { candidateId, removed }), candidate_id: candidateId, archive_hash: hash(stableJson(this.show(candidateId))), removed_worktrees: removed, branch_deleted: false as const, forced: false as const, confirmed_by: 'user' as const, completed_at: now(), payload_hash: '' }, 'payload_hash'); this.files.write(candidateId, `cleanup/${receipt.cleanup_id}.yaml`, receipt); this.update(candidateId, { status: 'ARCHIVED', baseline_path: null, candidate_path: null, main_fingerprint_after: this.mainFingerprint(manifest.repository.path) }); return receipt;
  }

  private assertProposal(proposal: ImprovementProposal): void { if (proposal.status !== 'approved_for_candidate') throw new DomainError('PROPOSAL_NOT_APPROVED', 'Candidate exige Proposal aprovada para candidate.'); if (!proposal.profile_scope.includes(this.profileId)) throw new DomainError('BLOCK_PROFILE', 'Proposal não pertence ao profile ativo.'); if (proposal.target.type.toLowerCase().includes('memory') || proposal.target.type.toLowerCase().includes('connector')) throw new DomainError('BLOCK_RISK', 'Target pertence a memória ou capability externa e não entra na v0.5.'); }
  private repository(input: string): string { const path = resolve(input); if (!existsSync(path)) throw new DomainError('REPOSITORY_NOT_FOUND', 'Repositório não encontrado.'); return this.git(path, ['rev-parse', '--show-toplevel']); }
  private repositoryIdentity(repo: string): string { const common = this.git(repo, ['rev-parse', '--git-common-dir']); const remote = this.tryGit(repo, ['config', '--get', 'remote.origin.url']) ?? ''; return hash(stableJson({ root: repo, common: resolve(repo, common), remote: hash(remote) })); }
  private status(repo: string): string { return this.git(repo, ['status', '--porcelain=v1', '--untracked-files=all']); }
  private mainFingerprint(repo: string): string { const dirtyFiles = (this.tryGit(repo, ['ls-files', '--others', '--exclude-standard']) ?? '').split('\n').filter(Boolean).sort().map(path => { const full = join(repo, path); const stat = this.tryLstat(full); if (!stat) return { path, missing: true }; return { path, mode: stat.mode, hash: stat.isSymbolicLink() ? hash(readlinkSync(full)) : stat.isFile() ? hash(readFileSync(full)) : 'directory' }; }); return hash(stableJson({ head: this.git(repo, ['rev-parse', 'HEAD']), branch: this.tryGit(repo, ['symbolic-ref', '--short', '-q', 'HEAD']) ?? null, status: this.status(repo), tracked_diff: hash(this.tryGit(repo, ['diff', '--binary', 'HEAD']) ?? ''), cached_diff: hash(this.tryGit(repo, ['diff', '--cached', '--binary']) ?? ''), dirtyFiles })); }
  private assertMainUnchanged(manifest: CandidateManifest): void { if (this.mainFingerprint(manifest.repository.path) !== manifest.main_fingerprint_before) throw new DomainError('MAIN_CHECKOUT_CHANGED', 'Checkout principal mudou durante a candidate.'); }
  private normalizeAllowedPaths(paths: string[]): string[] { return [...new Set(paths.flatMap(path => path.split(',')).map(path => path.trim()).filter(Boolean).map(path => path.replaceAll('\\', '/')))].map(path => { if (isAbsolute(path) || path.split('/').includes('..') || path.startsWith('.git')) throw new DomainError('PATH_BLOCKED', 'Allowlist contém path absoluto, ascendente ou Git metadata.'); return path; }).sort(); }
  private matches(pattern: string, path: string): boolean { const escaped = pattern.replace(/[.+^${}()|[\]\\]/g, '\\$&').replace(/\*\*/g, ':::DOUBLE:::').replace(/\*/g, '[^/]*').replaceAll(':::DOUBLE:::', '.*'); return new RegExp(`^${escaped}$`).test(path) || (pattern.endsWith('/**') && path.startsWith(pattern.slice(0, -3))); }
  private slug(value: string): string { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 32) || 'candidate'; }
  private environment(manifest: CandidateManifest, baseline: string): EnvironmentManifest { const lockfiles: Record<string, string> = {}; for (const name of ['package-lock.json', 'npm-shrinkwrap.json', 'yarn.lock', 'pnpm-lock.yaml']) { const path = join(baseline, name); if (existsSync(path)) lockfiles[name] = hash(readFileSync(path)); } const packagePath = join(baseline, 'package.json'); const value: EnvironmentManifest = hashed({ schema_version: 1 as const, candidate_id: manifest.candidate_id, base_sha: manifest.repository.base_sha, platform: { os: process.platform, arch: process.arch, node: process.version, npm: this.tryExec('npm', ['--version']) ?? 'unavailable' }, lockfiles, network: 'denied' as const, setup: { source: 'base_commit' as const, script_hash: existsSync(packagePath) ? hash(readFileSync(packagePath)) : hash('no-package') }, environment_names: ['NODE_ENV'], isolation: { separate_tmp: true, separate_cache: true }, preflight: 'passed' as const, payload_hash: '' }, 'payload_hash'); const mode = this.git(baseline, ['ls-files', '--stage']).split('\n').some(line => line.startsWith('160000 ')); if (mode) throw new DomainError('SUBMODULES_UNSUPPORTED', 'Submodules estão fora do piloto v0.5.'); return value; }
  private assertAuthorization(manifest: CandidateManifest): void { const auth = this.authorization(manifest.candidate_id); if (auth.scope_hash !== null || !auth.allowed_operations.includes('candidate_write') || auth.base_sha !== manifest.repository.base_sha || auth.repository_identity !== manifest.repository.identity || auth.revision !== manifest.revision || new Date(auth.expires_at).getTime() <= Date.now()) throw new DomainError('AUTHORIZATION_EXPIRED', 'Autorização ausente, divergente ou expirada.'); }
  private assertFreezeAuthorization(manifest: CandidateManifest, scope: ScopeReport): void { const auth = this.freezeAuthorization(manifest.candidate_id); if (auth.scope_hash !== scope.diff_hash || auth.allowed_operations.length !== 1 || auth.allowed_operations[0] !== 'local_snapshot' || auth.base_sha !== manifest.repository.base_sha || auth.repository_identity !== manifest.repository.identity || auth.revision !== manifest.revision || new Date(auth.expires_at).getTime() <= Date.now()) throw new DomainError('FREEZE_AUTHORIZATION_REQUIRED', 'Freeze exige autorização humana vigente para o change set exato.'); }
  private assertFrozenCandidate(manifest: CandidateManifest): void { if (!manifest.snapshot || !manifest.candidate_path || this.git(manifest.candidate_path, ['rev-parse', 'HEAD']) !== manifest.snapshot.commit_sha || this.status(manifest.candidate_path).length) throw new DomainError('SNAPSHOT_DIRTY', 'Avaliação exige worktree limpa exatamente no snapshot congelado.'); }
  private evaluationWorktree(manifest: CandidateManifest, side: 'baseline' | 'candidate', sha: string): string { const path = join(this.files.dir(manifest.candidate_id), 'evaluation', `r${String(manifest.revision).padStart(3, '0')}`, side); if (existsSync(path)) throw new DomainError('WORKTREE_COLLISION', 'Worktree de avaliação anterior ainda existe; não será sobrescrita.'); ensurePrivateDirectory(dirname(path)); this.git(manifest.repository.path, ['worktree', 'add', '--detach', path, sha]); return path; }
  private removeEvaluationWorktree(repo: string, path: string): void { if (existsSync(path)) this.tryGit(repo, ['worktree', 'remove', path]); }
  private update(candidateId: string, patch: Partial<CandidateManifest>): CandidateManifest { const current = this.show(candidateId); const next = { ...current, ...patch }; this.files.write(candidateId, 'manifest.yaml', next); return next; }
  private runCheck(cwd: string): { available: boolean; status: 'passed' | 'failed' | 'blocked'; exit: number | null; duration: number } { const started = Date.now(); if (!existsSync(join(cwd, 'package.json')) || !this.networkSandboxAvailable()) return { available: false, status: 'blocked', exit: null, duration: 0 }; const cache = join(dirname(dirname(cwd)), 'sandbox-cache', basename(cwd)); ensurePrivateDirectory(cache); try { execFileSync('bwrap', ['--unshare-net', '--die-with-parent', '--ro-bind', '/', '/', '--bind', cwd, cwd, '--bind', cache, cache, '--tmpfs', '/tmp', '--proc', '/proc', '--dev', '/dev', '--chdir', cwd, '--setenv', 'TMPDIR', '/tmp', '--setenv', 'HOME', '/tmp', '--setenv', 'npm_config_cache', cache, '--', 'npm', 'run', 'check'], { cwd, env: { PATH: process.env.PATH ?? '', CI: '1', NODE_ENV: 'test', npm_config_offline: 'true', npm_config_update_notifier: 'false' }, stdio: ['ignore', 'pipe', 'pipe'], timeout: 120_000, maxBuffer: 2_000_000 }); return { available: true, status: 'passed', exit: 0, duration: Date.now() - started }; } catch (error: unknown) { const exit = this.childStatus(error); return { available: exit !== null, status: exit === null ? 'blocked' : 'failed', exit, duration: Date.now() - started }; } }
  private tryGit(cwd: string, args: string[]): string | undefined { try { return this.git(cwd, args); } catch { return undefined; } }
  private tryLstat(path: string): ReturnType<typeof lstatSync> | undefined { try { return lstatSync(path); } catch { return undefined; } }
  private tryExec(command: string, args: string[]): string | undefined { try { return execFileSync(command, args, { encoding: 'utf8', env: this.safeEnv(), stdio: ['ignore', 'pipe', 'ignore'] }).trim(); } catch (error: unknown) { return this.childStatus(error) === 0 ? this.childStdout(error).trim() : undefined; } }
  private networkSandboxAvailable(): boolean { try { execFileSync('bwrap', ['--unshare-net', '--die-with-parent', '--ro-bind', '/', '/', '--tmpfs', '/tmp', '--proc', '/proc', '/bin/true'], { env: this.safeEnv(), stdio: ['ignore', 'ignore', 'ignore'], timeout: 5_000 }); return true; } catch { return false; } }
  private assertNetworkSandbox(): void { if (!this.networkSandboxAvailable()) throw new DomainError('ENVIRONMENT_ISOLATION_UNAVAILABLE', 'Network sandbox indisponível; a candidate foi bloqueada antes de criar worktree.'); }
  private assertNoActiveHooks(repo: string): void { const configured = this.tryGit(repo, ['config', '--get', 'core.hooksPath']); if (configured) throw new DomainError('HOOKS_UNSUPPORTED', 'Hooks configurados exigem preflight isolado e não são executados no piloto.'); const common = this.git(repo, ['rev-parse', '--git-common-dir']); const hooks = join(resolve(repo, common), 'hooks'); if (!existsSync(hooks)) return; const active = readdirSync(hooks).some(name => { const path = join(hooks, name); const stat = this.tryLstat(path); return Boolean(stat?.isFile() && (Number(stat.mode) & 0o111)); }); if (active) throw new DomainError('HOOKS_UNSUPPORTED', 'Hooks executáveis exigem preflight isolado e não são executados no piloto.'); }
  private childStatus(error: unknown): number | null { return typeof error === 'object' && error !== null && 'status' in error && typeof error.status === 'number' ? error.status : null; }
  private childStdout(error: unknown): string { if (typeof error === 'object' && error !== null && 'stdout' in error) { const value = error.stdout; return typeof value === 'string' ? value : value instanceof Uint8Array ? Buffer.from(value).toString('utf8') : ''; } return ''; }
  private safeEnv(extra: NodeJS.ProcessEnv = {}): NodeJS.ProcessEnv { return { PATH: process.env.PATH ?? '', GIT_TERMINAL_PROMPT: '0', GIT_CONFIG_NOSYSTEM: '1', GIT_CONFIG_GLOBAL: '/dev/null', ...extra }; }
  private git(cwd: string, args: string[], extraEnv: NodeJS.ProcessEnv = {}): string { const forbidden = ['fetch', 'pull', 'push', 'merge', 'rebase', 'cherry-pick', 'remote', 'reset', 'clean', 'prune', 'tag', 'config --global', 'config --system']; if (args.some(arg => forbidden.includes(arg))) throw new DomainError('GIT_OPERATION_BLOCKED', 'Operação Git não é capacidade da v0.5.'); try { return execFileSync('git', args, { cwd, env: this.safeEnv(extraEnv), encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], maxBuffer: 2_000_000 }).trim(); } catch (error: unknown) { if (this.childStatus(error) === 0) return this.childStdout(error).trim(); throw new DomainError('GIT_OPERATION_FAILED', 'Operação Git local não pôde ser concluída.'); } }
  private markdown(report: ImpactReport, comparison: RegressionComparison, review: CodeReviewReport): string { return [`# Impact Report ${report.candidate_id}`, '', `- Proposal: ${report.proposal_ref}`, `- Base: ${report.base_sha}`, `- Snapshot: ${report.snapshot_commit}`, `- Recommendation: ${report.recommendation}`, `- Hard gates: ${report.hard_gates_passed ? 'passed' : 'blocked'}`, `- Comparison: ${comparison.comparison_hash}`, `- Review: ${review.review_hash}`, '', '## Changed paths', '', ...report.changed_paths.map(path => `- ${path}`), '', '## Limitations', '', ...report.limitations.map(item => `- ${item}`), ''].join('\n'); }
}
